// <auto-generated />
namespace CodedenimWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_CourseEnrollment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_CourseEnrollment));
        
        string IMigrationMetadata.Id
        {
            get { return "201710081705334_Create_CourseEnrollment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
