// <auto-generated />
namespace CodedenimWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Created_the_Seed_Methods : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Created_the_Seed_Methods));
        
        string IMigrationMetadata.Id
        {
            get { return "201709051015516_Created_the_Seed_Methods"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
