// <auto-generated />
namespace CodedenimWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Commented_theEmail_IsuniqueAttr : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Commented_theEmail_IsuniqueAttr));
        
        string IMigrationMetadata.Id
        {
            get { return "201710080302187_Commented_theEmail_IsuniqueAttr"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
