// <auto-generated />
namespace CodedenimWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeFieldsOnPaymentType_Mistake : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeFieldsOnPaymentType_Mistake));
        
        string IMigrationMetadata.Id
        {
            get { return "201710070210338_removeFieldsOnPaymentType_Mistake"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
