// <auto-generated />
namespace CodedenimWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changed_intTo_intOFArrayIn_assignCourses1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changed_intTo_intOFArrayIn_assignCourses1));
        
        string IMigrationMetadata.Id
        {
            get { return "201711092052042_changed_intTo_intOFArrayIn_assignCourses1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
