// <auto-generated />
namespace CodedenimWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addedUserID_in_PaymentTable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedUserID_in_PaymentTable));
        
        string IMigrationMetadata.Id
        {
            get { return "201710070321085_addedUserID_in_PaymentTable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
